### ISSUE TITLE
Same domain, different port

### ISSUE THREAD

**Issue by buglinjo** [adonisjs/adonis-cors#10]
I'm using Adonisjs as API service for my React project. React is running on `80` port and Adonisjs - `8080`. When I send requests from React, Cors is blocking it. I tried adding to `origin: 'domain.com:8080` in cors config file. Also tried: `origin: ['domain.com:8080']` and `origin: ['domain.com']` but still every request is blocked in Chrome. Only thing works is to set `origin: true`.

**Comment by thetutlage** [comment]
You have to pass the port for the React app and not the Adonis app.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
