### ISSUE TITLE
Feature request - HTTP OPTIONS SHOULD allow body in response

### ISSUE THREAD

**Issue by tpoisseau** [adonisjs/adonis-cors#13]
Hello,

## Why this feature is required (specific use-cases will be appreciated)?
- https://tools.ietf.org/html/rfc2616#page-52
- https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.2
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

RFCs and docs i readed say that OPTIONS http request can include a body response.

### My specific use-case
I create an api for my work and I wanted document my API under OPTIONS route (with same url) and define in returned body the schema of request and response body.

With CORS Middleware activated, OPTIONS route handle request and return empty body in response before reach my controller.

## Have you tried any other work arounds?
For now, my work around is to disable CORS middleware...

## Are you willing to work on it with little guidance?
I can try too fix it, but I don't want to risk to break someone else existent code.

## Solution I suggest
https://github.com/adonisjs/adonis-cors/blob/develop/src/Cors/index.js#L278

replace handle function by 

```js
  async handle ({ request, response }, next) {
    this
      ._setOrigin(request.header('origin'), response)
      ._setCredentials(response)
      ._setExposeHeaders(response)

    /**
     * If request is OPTIONS set CORS headers before call next.
     */
    if (request.method() === 'OPTIONS') {
      this
        ._setMethods(response)
        ._setHeaders(request.header('access-control-request-headers'), response)
        ._setMaxAge(response)
    }

    return next()
  }
```

## NB
I'm not really used to creating issues, so I hope I did it right :wink:

**Comment by thetutlage** [comment]
I believe this can be achieved by creating your own `Cors` middleware, which extends the inbuilt CORS middleware.

```js
const Cors = use('App/Middleware/Cors')

class AppCors extends Cors {
  async handle ({ request, response }, next) {
    this
      ._setOrigin(request.header('origin'), response)
      ._setCredentials(response)
      ._setExposeHeaders(response)

      if (request.method() === 'OPTIONS') {
        this
          ._setMethods(response)
          ._setHeaders(request.header('access-control-request-headers'), response)
          ._setMaxAge(response)
      }

      await next()    
  }
}

module.exports = AppCors
```

and then inside `start/kernel.js` file, you must register your own middleware and remove the existing one

**Comment by thetutlage** [comment]
Closing, since no response from the creator

**Comment by tpoisseau** [comment]
Hi, sorry for not having aswered.
I've solved my issue with your response. But I think the cors middleware should allow body response on OPTION verb, because it's allowed by http specification.

Feel free to accept my linked pr.

Best regards.

**Comment by safavie** [comment]
@thetutlage
I have this error in my Middleware:
Class extends value # is not a constructor or null
My code is :

const Cors = use(‘Adonis/Middleware/Cors’)

class Origin extends Cors {
async handle ({ request, response }, next) {
console.log(request.headers())
this
._setOrigin(request.header(‘origin’), response)
._setCredentials(response)
._setExposeHeaders(response)

  if (request.method() === 'OPTIONS') {
    this
      ._setMethods(response)
      ._setHeaders(request.header('access-control-request-headers'), response)
      ._setMaxAge(response)
  }

  await next()
}
}

module.exports = Origin

**Comment by tpoisseau** [comment]
Maybe the cors middleware is not declared in your bootstrap server file (I don't remember the name) so  `use(‘Adonis/Middleware/Cors’)` returning null ?

**Comment by safavie** [comment]
> returning null ?
returning this:
Cors {
  options:
   { origin: [Function: name],
     methods: [ 'GET', 'PUT', 'PATCH', 'POST', 'DELETE' ],
     headers: true,
     exposeHeaders: true,
     credentials: true,
     maxAge: 90 } }
