### ISSUE TITLE
Access-Control-Allow-Origin not being set correctly (undefined)

### ISSUE THREAD

**Issue by mhingston** [adonisjs/adonis-cors#3]
Hi,

I'm using [adonis-fullstack-app/](https://github.com/adonisjs/adonis-fullstack-app/). If I change `config/cors.js` to have use `origin: '*'` when I run the server and check the headers being sent back, `Access-Control-Allow-Origin` is `undefined`.

![image](https://user-images.githubusercontent.com/9764437/30317258-7ea3d78e-97a1-11e7-9ff7-ab4089e624ab.png)

**Comment by thetutlage** [comment]
That happens coz `*` allows the current request origin, when making request from postman, there is no `Origin` header is sent.

Try it from browser it should work fine

**Comment by mhingston** [comment]
Thanks, missed that.
